# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'butce.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(779, 439)
        MainWindow.setStyleSheet("QPushButton {\n"
"    background-color: #f7f7f7;\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 10px;\n"
"    padding: 10px 20px;\n"
"    color: #333;\n"
"    font-family: \"Helvetica Neue\", sans-serif;\n"
"    font-size: 10px;\n"
"    font-weight: 400;\n"
"    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);\n"
"    transition: 0.2s ease-in-out;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #fafafa;\n"
"    border-color: #bbb;\n"
"    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #f5f5f5;\n"
"    border-color: #aaa;\n"
"    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QLineEdit {\n"
"    background-color: #f7f7f7;\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    color: #333;\n"
"    font-family: \"Helvetica Neue\", sans-serif;\n"
"    font-size: 11px;\n"
"    font-weight: 400;\n"
"    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);\n"
"    transition: 0.2s ease-in-out;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #fafafa;\n"
"    border-color: #bbb;\n"
"    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);\n"
"    font-size: 11px; /* Yazı boyutunu odaklanmış halde de belirleyin */\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QTableWidget {\n"
"    background-color: #f7f7f7;\n"
"    border: 1px solid #ddd;\n"
"    border-radius: 4px;\n"
"    font-family: \"Helvetica Neue\", sans-serif;\n"
"    font-size: 11px;\n"
"    font-weight: 400;\n"
"    color: #333;\n"
"    gridline-color: #ddd;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 741, 321))
        self.tableWidget.setRowCount(31)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        self.btnListele = QtWidgets.QPushButton(self.centralwidget)
        self.btnListele.setGeometry(QtCore.QRect(300, 350, 151, 41))
        self.btnListele.setObjectName("btnListele")
        self.bitTarih = QtWidgets.QDateEdit(self.centralwidget)
        self.bitTarih.setGeometry(QtCore.QRect(160, 350, 121, 41))
        self.bitTarih.setMinimumDate(QtCore.QDate(2022, 9, 14))
        self.bitTarih.setCalendarPopup(True)
        self.bitTarih.setDate(QtCore.QDate(2024, 1, 1))
        self.bitTarih.setObjectName("bitTarih")
        self.basTarih = QtWidgets.QDateEdit(self.centralwidget)
        self.basTarih.setGeometry(QtCore.QRect(20, 350, 121, 41))
        self.basTarih.setMinimumDate(QtCore.QDate(2022, 9, 14))
        self.basTarih.setCalendarPopup(True)
        self.basTarih.setDate(QtCore.QDate(2024, 1, 1))
        self.basTarih.setObjectName("basTarih")
        self.lblToplamGider = QtWidgets.QLabel(self.centralwidget)
        self.lblToplamGider.setGeometry(QtCore.QRect(510, 350, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Caslon Pro Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lblToplamGider.setFont(font)
        self.lblToplamGider.setStyleSheet("color:rgb(198, 51, 53)")
        self.lblToplamGider.setText("")
        self.lblToplamGider.setObjectName("lblToplamGider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 779, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tarihe Göre Listele"))
        self.btnListele.setText(_translate("MainWindow", "TARİHE GÖRE LİSTELE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
