# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hizli_notlar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(398, 458)
        Form.setStyleSheet("\n"
"        QListWidget::item {\n"
"            height: 20px; /* Örnek satır yüksekliği, kendinize göre ayarlayın */ \n"
"        }\n"
"")
        self.lstListe = QtWidgets.QListWidget(Form)
        self.lstListe.setGeometry(QtCore.QRect(20, 100, 341, 291))
        self.lstListe.setObjectName("lstListe")
        self.lneKayit = QtWidgets.QLineEdit(Form)
        self.lneKayit.setGeometry(QtCore.QRect(50, 40, 171, 41))
        self.lneKayit.setObjectName("lneKayit")
        self.btnEkle = QtWidgets.QPushButton(Form)
        self.btnEkle.setGeometry(QtCore.QRect(250, 40, 101, 41))
        self.btnEkle.setObjectName("btnEkle")
        self.btnSil = QtWidgets.QPushButton(Form)
        self.btnSil.setGeometry(QtCore.QRect(130, 400, 161, 41))
        self.btnSil.setObjectName("btnSil")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Hızlı Notlar"))
        self.btnEkle.setText(_translate("Form", "EKLE"))
        self.btnSil.setText(_translate("Form", "SİL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
